module.exports = {
  SOCKET_ERROR: {
    "00001": "The IoT device does not exist",
    "00002": "The IoT device already exists, and it is added repeatedly",
    "00003": "Repeat instructions",
    "00004": "Invalid Instructions",
    "00005": "There are no permissions",
    "00006": "Format error",
    "00007": "Illegal parameters",
    "00008": "There are too many request parameters",
  },

  SOCKET_RESULT: {
    SUCCESS: 0,
    FAIL: 1,
  },

  SOCKET_REQUEST: {
    login: "login",
    heartbeat: "heartbeat",
    addDevice: "addDevice",
    delDevice: "delDevice",
    switch: "switch",
    battery: "battery",
    alarm: "alarm",
    reportDeviceMode: "reportDeviceMode",
    deviceListVersion: "deviceListVersion",
    deviceList: "deviceList",
    cityList: "cityList",
    weather: "weather",
    ntp: "ntp",
    light: "light",
    deviceMode: "deviceMode",
    deviceLocation: "deviceLocation",
    deviceName: "deviceName",
    LTSVersion: "LTSVersion",
    upgrade: "upgrade",
    firmwareInfo: "firmwareInfo",
    upgradeAck: "upgradeAck",
    lightAck: "lightAck",
    deviceModeAck: "deviceModeAck",
    deviceLocationAck: "deviceLocationAck",
    deviceNameAck: "deviceNameAck",
    changePasswordAck: "changePasswordAck",
  },

  DEVICE_CODES: {
    gateway: ["NLG"],
    lights: [
      "Z3L",
      "NLD",
      "NLFE",
      "NLIS",
      "NLM",
      "NLF",
      "NLL",
      "NLFN",
      "BNIL",
      "BNLD",
      "BN3L",
    ],
    ventilation: ["NLLF"],
    power: [
      "NLAS",
      "NLPD",
      "NLPO",
      "NLPT",
      "NLPC",
      "NLGS",
      "NLE",
      "NLC",
      "NLPM",
      "NLP",
      "NLPS",
      "BNCS",
      "BNXM",
    ],
    heating: ["BNTH", "BNTR", "BNFC"],
    rollerShutter: [
      "NLTV",
      "Z3V",
      "NLIV",
      "NLAV",
      "NLV",
      "NLLV",
      "BNAB",
      "BNAS",
      "BNMS",
    ],
    scenario: ["NLAO", "NLPD", "NLT"],
    thermostat: ["BNS"],
    lock: ["BNLO"],
    fan: ["LFCA"],
    airConditioner: ["BAC"],
  },
  SET_STATE_ACTION: {
    turnOnLight: "Turn on the light",
    changeBrightness: "Change brightness of the light",
    openCurtain: "Open the curtain",
    chageTemperatureSetpoint: "Apply a temperature set point to a room",
    changeFanSpeed: "Change fan speed",
  },
  ELECTRICITY_TYPE:
    "sum_energy_self_consumption,sum_energy_buy_from_grid,sum_energy_buy_from_grid$0,sum_energy_buy_from_grid$1,sum_energy_buy_from_grid$2,sum_energy_buy_from_grid$3,sum_energy_buy_from_grid$4,sum_energy_buy_from_grid$5,sum_energy_buy_from_grid$6,sum_energy_buy_from_grid$7,sum_energy_buy_from_grid$8,sum_energy_buy_from_grid$9,sum_energy_buy_from_grid$10,sum_energy_buy_from_grid$11,sum_energy_buy_from_grid_price$0,sum_energy_buy_from_grid_price$1,sum_energy_buy_from_grid_price$2,sum_energy_buy_from_grid_price$3,sum_energy_buy_from_grid_price$4,sum_energy_buy_from_grid_price$5,sum_energy_buy_from_grid_price$6,sum_energy_buy_from_grid_price$7,sum_energy_buy_from_grid_price$8,sum_energy_buy_from_grid_price$9,sum_energy_buy_from_grid_price$10,sum_energy_buy_from_grid_price$11,sum_energy_elec,sum_energy_price$0,sum_energy_price$1,sum_energy_price$2,sum_energy_elec$2,sum_energy_elec$0,sum_energy_elec$1",
  SCENARIO_TYPE: {
    home: "Home",
    away: "Away",
    wake_up: "Wake Up",
    bedtime: "Bed Time",
    other: "Other",
  },
};
